//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("M2M4RiaDemoModel", "DogTrainer", "Dog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(M2M4RiaDemo.Web.Model.Dog), "Trainer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(M2M4RiaDemo.Web.Model.Trainer))]

#endregion

namespace M2M4RiaDemo.Web.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class M2M4RiaDemoModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new M2M4RiaDemoModelContainer object using the connection string found in the 'M2M4RiaDemoModelContainer' section of the application configuration file.
        /// </summary>
        public M2M4RiaDemoModelContainer() : base("name=M2M4RiaDemoModelContainer", "M2M4RiaDemoModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new M2M4RiaDemoModelContainer object.
        /// </summary>
        public M2M4RiaDemoModelContainer(string connectionString) : base(connectionString, "M2M4RiaDemoModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new M2M4RiaDemoModelContainer object.
        /// </summary>
        public M2M4RiaDemoModelContainer(EntityConnection connection) : base(connection, "M2M4RiaDemoModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Trainer> Trainers
        {
            get
            {
                if ((_Trainers == null))
                {
                    _Trainers = base.CreateObjectSet<Trainer>("Trainers");
                }
                return _Trainers;
            }
        }
        private ObjectSet<Trainer> _Trainers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dog> Dogs
        {
            get
            {
                if ((_Dogs == null))
                {
                    _Dogs = base.CreateObjectSet<Dog>("Dogs");
                }
                return _Dogs;
            }
        }
        private ObjectSet<Dog> _Dogs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Trainers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrainers(Trainer trainer)
        {
            base.AddObject("Trainers", trainer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDogs(Dog dog)
        {
            base.AddObject("Dogs", dog);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="M2M4RiaDemoModel", Name="Dog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dog object.
        /// </summary>
        /// <param name="chasesCars">Initial value of the ChasesCars property.</param>
        /// <param name="dogId">Initial value of the DogId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Dog CreateDog(global::System.Boolean chasesCars, global::System.Int32 dogId, global::System.String name)
        {
            Dog dog = new Dog();
            dog.ChasesCars = chasesCars;
            dog.DogId = dogId;
            dog.Name = name;
            return dog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ChasesCars
        {
            get
            {
                return _ChasesCars;
            }
            set
            {
                OnChasesCarsChanging(value);
                ReportPropertyChanging("ChasesCars");
                _ChasesCars = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChasesCars");
                OnChasesCarsChanged();
            }
        }
        private global::System.Boolean _ChasesCars;
        partial void OnChasesCarsChanging(global::System.Boolean value);
        partial void OnChasesCarsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DogId
        {
            get
            {
                return _DogId;
            }
            set
            {
                if (_DogId != value)
                {
                    OnDogIdChanging(value);
                    ReportPropertyChanging("DogId");
                    _DogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DogId");
                    OnDogIdChanged();
                }
            }
        }
        private global::System.Int32 _DogId;
        partial void OnDogIdChanging(global::System.Int32 value);
        partial void OnDogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("M2M4RiaDemoModel", "DogTrainer", "Trainer")]
        public EntityCollection<Trainer> Trainers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Trainer>("M2M4RiaDemoModel.DogTrainer", "Trainer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Trainer>("M2M4RiaDemoModel.DogTrainer", "Trainer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="M2M4RiaDemoModel", Name="Trainer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Trainer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Trainer object.
        /// </summary>
        /// <param name="trainerId">Initial value of the TrainerId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Trainer CreateTrainer(global::System.Int32 trainerId, global::System.String name)
        {
            Trainer trainer = new Trainer();
            trainer.TrainerId = trainerId;
            trainer.Name = name;
            return trainer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TrainerId
        {
            get
            {
                return _TrainerId;
            }
            set
            {
                if (_TrainerId != value)
                {
                    OnTrainerIdChanging(value);
                    ReportPropertyChanging("TrainerId");
                    _TrainerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TrainerId");
                    OnTrainerIdChanged();
                }
            }
        }
        private global::System.Int32 _TrainerId;
        partial void OnTrainerIdChanging(global::System.Int32 value);
        partial void OnTrainerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("M2M4RiaDemoModel", "DogTrainer", "Dog")]
        public EntityCollection<Dog> Dogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dog>("M2M4RiaDemoModel.DogTrainer", "Dog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dog>("M2M4RiaDemoModel.DogTrainer", "Dog", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
